### PR TITLE
add pipeline for QC + alignment

### PR DESCRIPTION
**Pull request by nbokulich**
Unit tests are left out of this PR, pending #10 (as follow-up from #7 ) — will use the same test data and expected outputs as #7 .

Currently this only uses paired-end data (see #7 ) — will add single-end support in the future.

Do we want to expose all options, as I have done here, or should we restrict some params to defaults?

### CODE REVIEW

**Comment by gregcaporaso** [comment]
That is a lot of parameters! I think it might be a good idea to restrict this to a small set, and let users go to the underlying `Actions` if they want full control over the parameter settings. 

Should we merge this, and then think about which parameters we want to restrict to when we finalize the unit tests and re-visit the types? We could do a full review at that time too.

**Comment by nbokulich** [comment]
It is a lot! I was thinking we would test this out a bit before narrowing to the list of parameters in greatest need of adjustment... perhaps with Jason's input.

**Comment by gregcaporaso** [comment]
That's a good plan.

**Review by gregcaporaso — APPROVED** [review]
@nbokulich, I did a quick review of this and it's looking good to me. I think we should merge, and then do a full review of all code after unit tests are in (and before we're thinking of removing our README from the disclaimer). Objections to that approach? 

One question: why do you return `filtered_seqs` and `clean_seqs` from `filter_clean_consensus`? I would expect it to return either just `clean_seqs` (i.e., the final output of all of the QC steps) or `filtered_seqs`, `cut_seqs`, and `clean_seqs` (i.e., the output of each individual QC step).

**Comment by nbokulich** [comment]
Sounds good to me @gregcaporaso 

> why do you return filtered_seqs and clean_seqs from filter_clean_consensus?
My thinking was this: filtered_seqs would be after cleaning of, e.g., human reads, so "raw" data fit to publish; but then clean_seqs is the jumping-off point for other downstream analyses.

Another sensible option would be to drop the initial filtering step, leave that up to the user to decide if they want it.

**Pull request merged**
